server:
  port: 9099
spring:
  application:
    name: sampleconfigserver
  cloud:
    config:
      server:
        native:
          searchLocations:  file:///C:/SampleConfig/mongorepo
  profiles:
    active: native
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://host.docker.internal:9091/eureka
ribbon:
  eureka:
    enabled: true        