spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: testmongodb 
eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://host.docker.internal:9091/eureka
ribbon:
  eureka:
    enabled: true